// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTfulAPI.Persistence;

#nullable disable

namespace RESTfulAPI.Persistence.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808185917_Baseline_App")]
    partial class Baseline_App
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("HeadOfDept")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED071A70BF");

                    b.HasIndex(new[] { "Name" }, "UQ__Departme__737584F6053E0117")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.InsuranceProvider", b =>
                {
                    b.Property<int>("InsuranceProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceProviderId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("InsuranceProviderId")
                        .HasName("PK__Insuranc__D6084635429E61DA");

                    b.HasIndex(new[] { "Name" }, "UQ__Insuranc__737584F60072F5B3")
                        .IsUnique();

                    b.ToTable("InsuranceProviders");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("InsurancePolicyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InsuranceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("PatientId")
                        .HasName("PK__Patients__970EC366E74E80FE");

                    b.HasIndex("InsuranceProviderId");

                    b.HasIndex(new[] { "MedicalRecordNumber" }, "UQ__Patients__8E549ED05C9BE46D")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("InsuranceClaimNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte>("PaymentMethodId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A38F24B00E8");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Payments_DepartmentId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Payments_PatientId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<byte>("PaymentMethodId")
                        .HasColumnType("tinyint");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__DC31C1D3000EB8DA");

                    b.HasIndex(new[] { "MethodName" }, "UQ__PaymentM__218CFB1752AA4271")
                        .IsUnique();

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Patient", b =>
                {
                    b.HasOne("RESTfulAPI.Domain.Entities.InsuranceProvider", "InsuranceProvider")
                        .WithMany("Patients")
                        .HasForeignKey("InsuranceProviderId")
                        .HasConstraintName("FK_Patients_InsuranceProviders");

                    b.Navigation("InsuranceProvider");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RESTfulAPI.Domain.Entities.Department", "Department")
                        .WithMany("Payments")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Departments");

                    b.HasOne("RESTfulAPI.Domain.Entities.Patient", "Patient")
                        .WithMany("Payments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Patients");

                    b.HasOne("RESTfulAPI.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_PaymentMethods");

                    b.Navigation("Department");

                    b.Navigation("Patient");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Department", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.InsuranceProvider", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RESTfulAPI.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
