name: CI/CD API

# must grant id-token write so azure/login@v2 can fetch the GitHub OIDC token
permissions:
  id-token: write       # <-- allows azure/login to get ACTIONS_ID_TOKEN_REQUEST_URL
  contents: read        # <-- checkout needs read

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install EF Core global tool
        shell: pwsh
        run: dotnet tool install --global dotnet-ef --version 8.*

      - name: Build & Publish API
        shell: pwsh
        run: |
          dotnet build src/RESTfulAPI/RESTfulAPI.csproj --configuration Release
          dotnet publish src/RESTfulAPI/RESTfulAPI.csproj `
            --configuration Release `
            --output publish

      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment:     azurecloud
          auth-type:       SERVICE_PRINCIPAL

      - name: Apply EF Core migrations (both contexts)
        shell: pwsh
        env:
          PROD_SQL_CONN: ${{ secrets.PROD_SQL_CONN }}
        run: |
          # ensure dotnet-ef is on the PATH
          $Env:PATH += ";${Env:USERPROFILE}\.dotnet\tools"

          dotnet-ef database update `
            --context AppDbContext `
            --connection $Env:PROD_SQL_CONN `
            --project src/RESTfulAPI/RESTfulAPI.csproj `
            --startup-project src/RESTfulAPI/RESTfulAPI.csproj

          dotnet-ef database update `
            --context LogDbContext `
            --connection $Env:PROD_SQL_CONN `
            --project src/RESTfulAPI/RESTfulAPI.csproj `
            --startup-project src/RESTfulAPI/RESTfulAPI.csproj

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./publish
