name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dotnet-app artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install EF Core global tool
        shell: pwsh
        run: dotnet tool install --global dotnet-ef --version 8.*

      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: azurecloud
          auth-type: service-principal

      - name: Apply EF Core migrations (both contexts)
        shell: pwsh
        working-directory: src/RESTfulAPI
        env:
          # your connection string secret
          PROD_SQL_CONN: ${{ secrets.PROD_SQL_CONN }}
        run: |
          # ensure dotnet-ef is on the PATH
          $Env:PATH += ";${Env:USERPROFILE}\.dotnet\tools"

          # migrate the main AppDbContext
          dotnet-ef database update `
            --context AppDbContext `
            --connection $Env:PROD_SQL_CONN `
            --project RESTfulAPI.csproj `
            --startup-project RESTfulAPI.csproj

          # migrate the LogDbContext
          dotnet-ef database update `
            --context LogDbContext `
            --connection $Env:PROD_SQL_CONN `
            --project RESTfulAPI.csproj `
            --startup-project RESTfulAPI.csproj

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: src/RESTfulAPI/bin/Release/net8.0/publish
